// Renders the bash installer/uninstaller scripts that teammates curl|bash.
// The server URL is baked in at render time so the output is self-contained.
// Keep the scripts pure bash and dependency-free — they run on teammate Macs
// and on headless Linux VPSes with only base-system tooling.
//
// TWO SERVICE MODELS, ONE SCRIPT. `uname -s` selects a branch:
//   * Darwin → a per-user LaunchAgent (+ the v0.6.0 watchdog pair). This
//     branch is FROZEN: every line of the launchctl discipline below is a
//     production incident fix (docs/resilience.md). Change nothing here for
//     Linux's benefit.
//   * Linux  → a systemd unit, SYSTEM scope by default (see
//     resolve_linux_service_scope for why, and for the lingering trap that
//     makes the --user fallback the fallback).
// Anything else is refused with a clear message.
//
// Escaping: this is a TS template literal emitting bash. A literal `$` is
// written `\$`; JS `${...}` is reserved for render-time substitutions
// (server URL, LaunchAgent label).

// Legacy launchd label — fielded daemons depend on it; do not rename.
const LABEL = "sh.anara.leaderboard";

// systemd unit name. Not the launchd label: reverse-DNS labels are a launchd
// convention, and `systemctl status tokenleader` is what an operator types.
const UNIT = "tokenleader.service";

function trimTrailingSlash(url: string): string {
  return url.replace(/\/+$/, "");
}

export interface InstallScriptOpts {
  /** Banner subtitle (TOKENLEADER_TEAM_NAME). Display-only; sanitized so it
   *  cannot break the printf format. */
  teamName?: string;
  /** True when TOKENLEADER_JOIN_TOKEN is set: the script advertises
   *  `--join=<code>`. The code itself is NEVER baked in — /install is an
   *  unauthenticated route. */
  joinRequired?: boolean;
}

/** Strip anything that could escape a double-quoted printf format. */
function bashSafe(s: string): string {
  return s.replace(/[^A-Za-z0-9 ._-]/g, "");
}

// Bash preamble shared with the local-clone installer (scripts/install.sh):
// colors, banner, handle resolution, step helpers, verification, summary.
// The baked server URL can be overridden at run time via
// $TOKENLEADER_INSTALL_URL (staging).
function renderSharedBashPreamble(serverUrlLiteral: string, opts: InstallScriptOpts = {}): string {
  const subtitle = opts.teamName
    ? `${bashSafe(opts.teamName)} team token-usage leaderboard`
    : "team token-usage leaderboard";
  // Appended to the canonical flag-form one-liner (`bash -s -- --name=…`).
  const oneLinerJoin = opts.joinRequired ? " --join=<code>" : "";
  return `#!/usr/bin/env bash
# tokenleader self-serve installer.
# Generated by the tokenleader server at ${serverUrlLiteral}.
# Idempotent: safe to re-run. Installs a per-user background service — a
# LaunchAgent on macOS, a systemd unit on Linux — that posts token usage
# events to ${serverUrlLiteral}. The daemon generates its own per-user secret
# on first run (TOFU); no shared credential to copy around.
set -euo pipefail

SERVER_URL="\${TOKENLEADER_INSTALL_URL:-${serverUrlLiteral}}"
LABEL="${LABEL}"
WATCHDOG_LABEL="\${LABEL}.watchdog"
DOMAIN="gui/\$(id -u)"
UNIT="${UNIT}"

# --- color setup ----------------------------------------------------------
# Only emit ANSI when stdout is an interactive TTY. curl|bash usually keeps
# stdout pointed at the terminal so colors work; CI pipes get clean text.
if [ -t 1 ]; then
  C_RESET=\$'\\033[0m'
  C_BOLD=\$'\\033[1m'
  C_DIM=\$'\\033[2m'
  C_GREEN=\$'\\033[0;32m'
  C_RED=\$'\\033[0;31m'
  C_YELLOW=\$'\\033[0;33m'
  C_CYAN=\$'\\033[0;36m'
else
  C_RESET=""; C_BOLD=""; C_DIM=""
  C_GREEN=""; C_RED=""; C_YELLOW=""; C_CYAN=""
fi

die() {
  printf "%s%s%s\\n" "\$C_RED" "\$1" "\$C_RESET" >&2
  exit 1
}

# --- platform check -------------------------------------------------------
OS_NAME="\$(uname -s)"
case "\$OS_NAME" in
  Darwin) TL_OS="darwin" ;;
  Linux)  TL_OS="linux" ;;
  *) die "tokenleader supports macOS and Linux. Detected: \$OS_NAME." ;;
esac

# ASSET_KEY is BOTH the /bin asset suffix AND the manifest key.
#   darwin: the frozen bare arch ("arm64"/"x64") — the legacy TOP-LEVEL
#           manifest keys every fielded daemon consumes. Intel maps to "x64".
#   linux : the platform token ("linux-x64"/"linux-arm64") — additive keys
#           inside manifest.platforms.
RAW_ARCH="\$(uname -m)"
if [ "\$TL_OS" = "darwin" ]; then
  case "\$RAW_ARCH" in
    arm64)  ASSET_KEY="arm64"; ARCH_LABEL="Apple Silicon (arm64)" ;;
    x86_64) ASSET_KEY="x64";   ARCH_LABEL="Intel Mac (x86_64)" ;;
    *) die "Unsupported arch '\$RAW_ARCH'. Only arm64 and x86_64." ;;
  esac
else
  # Linux reports aarch64, NEVER arm64: before this branch existed every
  # Graviton / Ampere / Hetzner-ARM VPS was rejected as an unsupported arch.
  case "\$RAW_ARCH" in
    x86_64|amd64)  ASSET_KEY="linux-x64";   ARCH_LABEL="Linux x86_64" ;;
    aarch64|arm64) ASSET_KEY="linux-arm64"; ARCH_LABEL="Linux aarch64" ;;
    *) die "Unsupported arch '\$RAW_ARCH'. Only x86_64 and aarch64." ;;
  esac
fi

# --- linux service model --------------------------------------------------
# SYSTEM unit by default. A system unit starts at boot with no login at all
# and needs no logind, no lingering, no XDG_RUNTIME_DIR and no session bus;
# systemd fills HOME/USER/LOGNAME from the passwd entry for User=, so
# ~/.claude, ~/.codex, ~/.cursor and the state dir resolve exactly as they do
# under launchd. The --user unit is the fallback for when we cannot escalate,
# and it is only durable with lingering ON: without it a --user unit is killed
# roughly ten seconds after the SSH session ends — the classic headless-VPS
# failure. Force either with TOKENLEADER_SERVICE_SCOPE=system|user.
SUDO=""
SERVICE_SCOPE=""
SERVICE_USER=""
SERVICE_GROUP=""
TARGET_HOME=""

resolve_linux_service_scope() {
  if [ "\$(id -u)" = "0" ]; then
    # \`curl … | sudo bash\`: the daemon must run as the HUMAN, not root, or it
    # would tail root's empty ~/.claude and report nothing.
    SERVICE_USER="\${SUDO_USER:-root}"
  else
    SERVICE_USER="\$(id -un)"
    if sudo -n true 2>/dev/null; then SUDO="sudo -n"; fi
  fi

  SERVICE_SCOPE="\${TOKENLEADER_SERVICE_SCOPE:-}"
  if [ -z "\$SERVICE_SCOPE" ]; then
    if [ "\$(id -u)" = "0" ] || [ -n "\$SUDO" ]; then
      SERVICE_SCOPE="system"
    else
      SERVICE_SCOPE="user"
    fi
  fi
  case "\$SERVICE_SCOPE" in
    system|user) ;;
    *) die "TOKENLEADER_SERVICE_SCOPE must be 'system' or 'user' (got '\$SERVICE_SCOPE')." ;;
  esac
  if [ "\$SERVICE_SCOPE" = "system" ] && [ "\$(id -u)" != "0" ] && [ -z "\$SUDO" ]; then
    die "A system unit needs root. Re-run as: curl -fsSL \$SERVER_URL/install | sudo bash -s -- --name=<handle>
Or install a user unit instead (needs 'sudo loginctl enable-linger \$(id -un)' to survive logout):
  TOKENLEADER_SERVICE_SCOPE=user curl -fsSL \$SERVER_URL/install | bash -s -- --name=<handle>"
  fi
  if [ "\$SERVICE_SCOPE" = "user" ] && [ "\$(id -u)" = "0" ]; then
    die "TOKENLEADER_SERVICE_SCOPE=user cannot be installed as root — run it as the user who owns ~/.claude."
  fi

  SERVICE_GROUP="\$(id -gn "\$SERVICE_USER" 2>/dev/null || echo "\$SERVICE_USER")"
  if command -v getent >/dev/null 2>&1; then
    TARGET_HOME="\$(getent passwd "\$SERVICE_USER" | cut -d: -f6)"
  fi
  if [ -z "\$TARGET_HOME" ]; then
    TARGET_HOME="\$(awk -F: -v u="\$SERVICE_USER" '\$1==u{print \$6; exit}' /etc/passwd 2>/dev/null || true)"
  fi
  if [ -z "\$TARGET_HOME" ] && [ "\$SERVICE_USER" = "\$(id -un)" ]; then
    TARGET_HOME="\$HOME"
  fi
  [ -n "\$TARGET_HOME" ] || die "Couldn't resolve a home directory for '\$SERVICE_USER'."
}

if [ "\$TL_OS" = "darwin" ]; then
  TARGET_HOME="\$HOME"
  LOG_DIR="\$HOME/Library/Logs/anara-leaderboard"
  UNIT_PATH=""
  SYSTEM_UNIT_PATH=""
  USER_UNIT_PATH=""
  OTHER_UNIT_PATH=""
  TOTAL_STEPS=6
else
  resolve_linux_service_scope
  # XDG state, matching src/daemon/log.ts's Linux default exactly. The daemon
  # used to create a literal ~/Library/Logs on Linux boxes.
  LOG_DIR="\$TARGET_HOME/.local/state/anara-leaderboard"
  # Both scope paths are named ONCE. Every later check ("is the other scope
  # installed?", "could we remove it?") reads these two variables, so the
  # installer, the tests and the operator all mean the same two files.
  SYSTEM_UNIT_PATH="/etc/systemd/system/\$UNIT"
  USER_UNIT_PATH="\$TARGET_HOME/.config/systemd/user/\$UNIT"
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    UNIT_PATH="\$SYSTEM_UNIT_PATH"
    OTHER_UNIT_PATH="\$USER_UNIT_PATH"
  else
    UNIT_PATH="\$USER_UNIT_PATH"
    OTHER_UNIT_PATH="\$SYSTEM_UNIT_PATH"
  fi
  TOTAL_STEPS=5
fi

STDERR_LOG="\$LOG_DIR/stderr.log"
STDOUT_LOG="\$LOG_DIR/stdout.log"
BIN_DST="\$TARGET_HOME/.local/bin/anara-leaderboard"
PLIST="\$HOME/Library/LaunchAgents/\${LABEL}.plist"
WATCHDOG_PLIST="\$HOME/Library/LaunchAgents/\${WATCHDOG_LABEL}.plist"
STATE_DIR="\$TARGET_HOME/.local/share/anara-leaderboard"
# The Linux config store (src/daemon/env-file.ts): what the unit references
# via EnvironmentFile= and what the CLI reads to answer "who am I". On macOS
# the plist plays this role.
ENV_FILE="\$STATE_DIR/daemon.env"

# NO interactive prompts: /dev/tty semantics differ wildly across terminals
# under curl|bash. Sensible defaults + env overrides instead; re-running the
# installer is idempotent.

# --- banner + pre-flight --------------------------------------------------
DIVIDER="\${C_DIM}──────────────────────────────────────────────────────────────────\${C_RESET}"

print_banner() {
  local service_desc
  local bin_desc
  if [ "\$TL_OS" = "darwin" ]; then
    service_desc="LaunchAgent"
    # Tilde form, byte-identical to every previous release: \$BIN_DST expands
    # to /Users/<name>/… and leaks the username into screenshares. On Linux
    # the absolute path CARRIES information — the target user's home may not
    # be the home of whoever is running the installer under sudo.
    bin_desc="~/.local/bin/anara-leaderboard"
  else
    service_desc="systemd \$SERVICE_SCOPE unit (\$SERVICE_USER)"
    bin_desc="\$BIN_DST"
  fi
  printf "\\n"
  printf "  %stokenleader installer%s\\n" "\$C_BOLD" "\$C_RESET"
  printf "  %s${subtitle}%s\\n" "\$C_DIM" "\$C_RESET"
  printf "\\n"
  printf "  %sendpoint%s    %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
  printf "  %splatform%s    %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$ARCH_LABEL" "\$C_RESET"
  printf "  %shandle%s      %s%s%s  %s(from %s)%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$USER_NAME" "\$C_RESET" \\
    "\$C_DIM" "\$HANDLE_SOURCE" "\$C_RESET"
  printf "  %sinstalling%s  %s%s%s  +  %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$bin_desc" "\$C_RESET" "\$C_BOLD" "\$service_desc" "\$C_RESET"
  printf "\\n"
  printf "  %sto use a different handle, re-run with:%s\\n" "\$C_DIM" "\$C_RESET"
  printf "    %scurl -fsSL %s/install | bash -s -- --name=your-name${oneLinerJoin}%s\\n" \\
    "\$C_DIM" "\$SERVER_URL" "\$C_RESET"
  printf "\\n"
  printf "%s\\n" "\$DIVIDER"
  printf "\\n"
}

# --- pick leaderboard handle ----------------------------------------------
# Order: --name flag, TOKENLEADER_USER — always slugified, NEVER guessed.
# The handle is the machine's leaderboard identity; deriving it from \$USER
# silently registered junk handles (e.g. a full unix username) whenever the
# common \`VAR=… curl … | bash\` misfire dropped the env var on curl instead
# of bash. Explicit or abort.
slugify() {
  printf '%s' "\$1" \\
    | LC_ALL=C tr '[:upper:]' '[:lower:]' \\
    | LC_ALL=C sed -E 's/[^a-z0-9_-]+/-/g; s/-+/-/g; s/^-+//; s/-+\$//' \\
    | cut -c1-32
}

resolve_handle() {
  local raw="\${ARG_NAME:-}"
  local source="--name"
  if [ -z "\$raw" ]; then
    raw="\${TOKENLEADER_USER:-}"
    source="TOKENLEADER_USER"
  fi
  if [ -z "\$raw" ]; then
    printf "%sNo handle given — the handle is your leaderboard identity, so it must be explicit.%s\\n" \\
      "\$C_RED" "\$C_RESET" >&2
    printf "Re-run with your handle:\\n" >&2
    printf "  %scurl -fsSL %s/install | bash -s -- --name=your-handle${oneLinerJoin}%s\\n" \\
      "\$C_BOLD" "\$SERVER_URL" "\$C_RESET" >&2
    printf "%s(If you tried TOKENLEADER_USER=… curl … | bash: the env var lands on curl, not\\n" "\$C_DIM" >&2
    printf " on bash across the pipe — the --name flag form avoids that footgun.)%s\\n" "\$C_RESET" >&2
    exit 1
  fi
  USER_NAME="\$(slugify "\$raw")"
  if [ -z "\$USER_NAME" ]; then
    printf "%sHandle '%s' slugifies to nothing usable — use letters, digits, '-' or '_'.%s\\n" \\
      "\$C_RED" "\$raw" "\$C_RESET" >&2
    exit 1
  fi
  HANDLE_SOURCE="\$source"
  HANDLE_RAW="\$raw"
}

# --- parse args -----------------------------------------------------------
ARG_NAME=""
ARG_JOIN=""
ARG_COMPANY=""
ARG_LINK=""
while [ \$# -gt 0 ]; do
  case "\$1" in
    --name=*)     ARG_NAME="\${1#--name=}" ;;
    --name)       ARG_NAME="\${2:-}"; shift ;;
    --join=*)     ARG_JOIN="\${1#--join=}" ;;
    --join)       ARG_JOIN="\${2:-}"; shift ;;
    --company=*)  ARG_COMPANY="\${1#--company=}" ;;
    --company)    ARG_COMPANY="\${2:-}"; shift ;;
    --link=*)     ARG_LINK="\${1#--link=}" ;;
    --link)       ARG_LINK="\${2:-}"; shift ;;
    -h|--help)
      printf "tokenleader installer\\n\\n"
      printf "Usage: curl -fsSL %s/install | bash -s -- [--name=HANDLE] [--join=CODE] [--company=DOMAIN] [--link=CODE]\\n\\n" "\$SERVER_URL"
      printf "Options:\\n"
      printf "  --name=HANDLE     the leaderboard handle (required unless TOKENLEADER_USER is set)\\n"
      printf "  --join=CODE       join code for servers that gate new handles\\n"
      printf "  --company=DOMAIN  company affiliation shown on the leaderboard (e.g. anara.com)\\n"
      printf "  --link=CODE       pairing code to add this machine to a handle you already\\n"
      printf "                    own (mint one with 'tokenleader link' on the old machine)\\n"
      printf "  -h, --help        this message\\n"
      printf "\\nEnvironment overrides:\\n"
      printf "  TOKENLEADER_USER      same as --name (lower priority than the flag)\\n"
      printf "  TOKENLEADER_JOIN      same as --join (lower priority than the flag)\\n"
      printf "  TOKENLEADER_COMPANY   same as --company (lower priority than the flag)\\n"
      printf "  TOKENLEADER_LINK      same as --link (lower priority than the flag)\\n"
      printf "\\nLinux only:\\n"
      printf "  TOKENLEADER_SERVICE_SCOPE=system|user   systemd scope (default: system when\\n"
      printf "                        root/sudo is available, else a lingering user unit)\\n"
      exit 0
      ;;
    *) printf "Unknown argument: %s\\nRun with --help for usage.\\n" "\$1" >&2; exit 1 ;;
  esac
  shift
done

# Join code: flag wins over env. Written into the service's env below so the
# daemon can present it on its first claim of a new handle.
JOIN_CODE="\${ARG_JOIN:-\${TOKENLEADER_JOIN:-}}"

# Company affiliation: flag wins over env. Written into the service's env;
# sent raw by the daemon — the SERVER normalizes (lowercase bare hostname)
# and ignores invalid values.
COMPANY="\${ARG_COMPANY:-\${TOKENLEADER_COMPANY:-}}"

# Link code: flag wins over env. Written into the service's env; the daemon
# presents it on its first sync to join an already-claimed handle as an
# additional device (single use — inert afterwards).
LINK_CODE="\${ARG_LINK:-\${TOKENLEADER_LINK:-}}"

# --- spinner + step line --------------------------------------------------
# Each step renders on one line rewritten via \\r; finish redraws with ✓/✗.
SPINNER_PID=""

cleanup_spinner() {
  if [ -n "\$SPINNER_PID" ] && kill -0 "\$SPINNER_PID" 2>/dev/null; then
    kill "\$SPINNER_PID" 2>/dev/null || true
    wait "\$SPINNER_PID" 2>/dev/null || true
  fi
  SPINNER_PID=""
}

# Always reap the spinner on exit, even on Ctrl-C / unexpected failure.
trap 'cleanup_spinner; tput cnorm 2>/dev/null || true' EXIT INT TERM

step_start() {
  # step_start <n> <label>
  CUR_STEP_N="\$1"
  CUR_STEP_LABEL="\$2"
  if [ -t 1 ]; then
    tput civis 2>/dev/null || true
    (
      local frames='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
      local i=0
      while :; do
        local frame="\${frames:\$i:1}"
        printf "\\r  %s[%d/%d]%s %s %s…………%s %s%s%s" \\
          "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
          "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
          "\$C_CYAN" "\$frame" "\$C_RESET"
        i=\$(( (i + 1) % 10 ))
        sleep 0.08
      done
    ) &
    SPINNER_PID=\$!
    disown "\$SPINNER_PID" 2>/dev/null || true
  else
    # Non-TTY: just print the step opening line once.
    printf "  [%d/%d] %s … " "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$CUR_STEP_LABEL"
  fi
}

step_ok() {
  # step_ok [optional-trailing-note]
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[%d/%d]%s %s %s…………%s %s✓%s" \\
      "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
      "\$C_GREEN" "\$C_RESET"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then
      printf "  %s%s%s" "\$C_DIM" "\$1" "\$C_RESET"
    fi
    printf "\\n"
  else
    printf "ok"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then printf " (%s)" "\$1"; fi
    printf "\\n"
  fi
}

step_warn() {
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[%d/%d]%s %s %s…………%s %s!%s" \\
      "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
      "\$C_YELLOW" "\$C_RESET"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then
      printf "  %s%s%s" "\$C_YELLOW" "\$1" "\$C_RESET"
    fi
    printf "\\n"
  else
    printf "warn"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then printf " (%s)" "\$1"; fi
    printf "\\n"
  fi
}

step_fail() {
  # step_fail <hint-line>
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[%d/%d]%s %s %s…………%s %s✗%s\\n" \\
      "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
      "\$C_RED" "\$C_RESET"
  else
    printf "fail\\n"
  fi
  if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then
    printf "        %s↳ %s%s\\n" "\$C_RED" "\$1" "\$C_RESET" >&2
  fi
  exit 1
}

# --- step 3: prepare binary (macOS) ---------------------------------------
# The published binary is already ad-hoc signed under our own identifier at
# build time (scripts/build-daemon.sh), so macOS attributes the LaunchAgent to
# us rather than to bun's author. Here we only strip the quarantine xattr so
# launchd can exec it without a Gatekeeper prompt. Gatekeeper quarantine has
# no Linux analogue and \`xattr\` is not installed there, so the Linux branch
# skips this step entirely.
do_codesign() {
  step_start 3 "Preparing binary"
  xattr -cr "\$BIN_DST" 2>/dev/null || true
  step_ok
}

# --- launchctl registration discipline -------------------------------------
# Shared by the daemon and watchdog labels. launchctl bootout is ASYNC:
# bootstrapping too soon fails with "service already loaded", so wait for the
# old instance to disappear, then enable + bootstrap with retries. The final
# verdict is \`launchctl print\` (is the job loaded?), NOT bootstrap's exit
# code — a mid-retry "already loaded" IS success, which keeps re-runs over
# half-installed states idempotent. All targets pinned to gui/\$UID.
register_launch_agent() {
  # register_launch_agent <label> <plist-path>
  local label="\$1"
  local plist="\$2"
  launchctl bootout "\$DOMAIN/\$label" 2>/dev/null || true
  for _i in 1 2 3 4 5 6 7 8 9 10; do
    launchctl print "\$DOMAIN/\$label" >/dev/null 2>&1 || break
    sleep 0.5
  done
  launchctl enable "\$DOMAIN/\$label" 2>/dev/null || true
  for _i in 1 2 3 4 5; do
    if launchctl bootstrap "\$DOMAIN" "\$plist" 2>/dev/null; then break; fi
    sleep 1
  done
  launchctl print "\$DOMAIN/\$label" >/dev/null 2>&1
}

# --- step 4: launchagent --------------------------------------------------
write_plist_and_register() {
  step_start 4 "Registering LaunchAgent"

  # A reinstall must honor THIS server's URL: drop any daemon-written
  # endpoint override. The state dir (TOFU secret) survives reinstalls.
  rm -f "\$STATE_DIR/endpoint"

  # Optional join code → daemon env; entry exists only when provided.
  # plutil -lint below catches XML-special characters in a code.
  JOIN_PLIST_ENTRY=""
  if [ -n "\$JOIN_CODE" ]; then
    JOIN_PLIST_ENTRY="
        <key>TOKENLEADER_JOIN</key>
        <string>\$JOIN_CODE</string>"
  fi

  # Optional company affiliation → daemon env; same conditional-entry shape
  # as the join code, with the same plutil -lint backstop for XML specials.
  COMPANY_PLIST_ENTRY=""
  if [ -n "\$COMPANY" ]; then
    COMPANY_PLIST_ENTRY="
        <key>TOKENLEADER_COMPANY</key>
        <string>\$COMPANY</string>"
  fi

  # Optional device-link code → daemon env; same conditional-entry shape.
  LINK_PLIST_ENTRY=""
  if [ -n "\$LINK_CODE" ]; then
    LINK_PLIST_ENTRY="
        <key>TOKENLEADER_LINK</key>
        <string>\$LINK_CODE</string>"
  fi

  cat >"\$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>Program</key>
    <string>\${HOME}/.local/bin/anara-leaderboard</string>
    <key>ProgramArguments</key>
    <array>
        <string>\${HOME}/.local/bin/anara-leaderboard</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>TOKENLEADER_USER</key>
        <string>\${USER_NAME}</string>
        <key>TOKENLEADER_ENDPOINT</key>
        <string>\${SERVER_URL}</string>
        <key>TOKENLEADER_HOME</key>
        <string>\${HOME}/.local/share/anara-leaderboard</string>\${JOIN_PLIST_ENTRY}\${COMPANY_PLIST_ENTRY}\${LINK_PLIST_ENTRY}
        <key>HOME</key>
        <string>\${HOME}</string>
        <key>PATH</key>
        <string>\${HOME}/.local/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <!-- Unconditional: respawn on ANY exit, clean or crash. A {SuccessfulExit:false}
         dict strands the daemon whenever it exits 0 (e.g. the post-update restart)
         until the next login — the v0.5.x fleet-stuck incident. -->
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>ProcessType</key>
    <string>Background</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
    <key>StandardErrorPath</key>
    <string>\${HOME}/Library/Logs/anara-leaderboard/stderr.log</string>
    <key>WorkingDirectory</key>
    <string>\${HOME}</string>
</dict>
</plist>
PLIST_EOF
  chmod 600 "\$PLIST"
  if ! plutil -lint "\$PLIST" >/dev/null 2>&1; then
    step_fail "generated plist failed plutil -lint (see \$PLIST)"
  fi

  if ! register_launch_agent "\$LABEL" "\$PLIST"; then
    step_fail "launchctl bootstrap failed (run 'launchctl bootstrap \$DOMAIN \$PLIST' for the error)"
  fi
  launchctl kickstart -k "\$DOMAIN/\$LABEL" >/dev/null 2>&1 || true
  step_ok
}

# --- step 5: watchdog launchagent ------------------------------------------
# Second half of the v0.6.0 "Never Silent" watchdog pair (docs/resilience.md).
# The plist points at a HARDLINK of the daemon binary so a deleted or
# rolled-back daemon binary can't take the watchdog down with it. The XML is
# byte-identical to scripts/plist-templates.sh render_watchdog_plist and the
# daemon's renderer in src/daemon/watchdog.ts — change one, change all.
# Same registration discipline as the daemon label; a registration failure
# is a warning, not a failure — the daemon re-registers the watchdog at
# every boot and the server queues reinstall_watchdog for silent devices.
#
# macOS ONLY. On Linux the watchdog is deliberately ABSENT: systemd already
# supplies the supervision half that launchd's KeepAlive + plist-heal
# machinery had to reconstruct, and a second resident process would only add
# failure modes. The daemon reports watchdog_installed=null there and
# src/server/fleet.ts gates its reinstall_watchdog sweep on the platform, so
# absence never reads as "degraded".
write_watchdog_plist_and_register() {
  step_start 5 "Registering watchdog"
  # Same filesystem as \$BIN_DST by construction; -f replaces a stale link.
  if ! ln -f "\$BIN_DST" "\$BIN_DST.watchdog" 2>/dev/null; then
    step_warn "couldn't hardlink \$BIN_DST.watchdog (daemon retries at every boot)"
    return 0
  fi

  cat >"\$WATCHDOG_PLIST" <<WATCHDOG_PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>sh.anara.leaderboard.watchdog</string>
    <key>ProgramArguments</key>
    <array>
        <string>\${HOME}/.local/bin/anara-leaderboard.watchdog</string>
        <string>watchdog</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>\${HOME}</string>
        <key>PATH</key>
        <string>\${HOME}/.local/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <!-- One-shot checker on launchd's clock: StartInterval fires while awake
         (collided/asleep firings are dropped, never queued) and RunAtLoad
         covers login. Deliberately NO KeepAlive - the watchdog must stay a
         short-lived one-shot; a resident copy would share the daemon's
         wedgeable-runtime failure domain. -->
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>120</integer>
    <key>ProcessType</key>
    <string>Background</string>
    <key>StandardOutPath</key>
    <string>\${HOME}/Library/Logs/anara-leaderboard/watchdog.log</string>
    <key>StandardErrorPath</key>
    <string>\${HOME}/Library/Logs/anara-leaderboard/watchdog.log</string>
</dict>
</plist>
WATCHDOG_PLIST_EOF
  chmod 600 "\$WATCHDOG_PLIST"
  if ! plutil -lint "\$WATCHDOG_PLIST" >/dev/null 2>&1; then
    step_fail "generated watchdog plist failed plutil -lint (see \$WATCHDOG_PLIST)"
  fi

  if register_launch_agent "\$WATCHDOG_LABEL" "\$WATCHDOG_PLIST"; then
    step_ok
  else
    step_warn "watchdog not registered (daemon retries at every boot; try 'launchctl print \$DOMAIN/\$WATCHDOG_LABEL')"
  fi
}

# --- step 6: start daemon (macOS) -----------------------------------------
# Don't block on "tick_done" — a first sync can take 10-60s on big
# histories. Confirm the process is running; sync continues in background.
wait_for_first_tick() {
  step_start 6 "Starting daemon"
  launchctl kickstart -k "\$DOMAIN/\$LABEL" >/dev/null 2>&1 || true

  local deadline=\$(( \$(date +%s) + 5 ))
  local state=""
  while [ "\$(date +%s)" -lt "\$deadline" ]; do
    state="\$(launchctl print "\$DOMAIN/\$LABEL" 2>/dev/null | awk -F'= *' '/^[[:space:]]*state /{print \$2; exit}' | tr -d ' ')"
    if [ "\$state" = "running" ]; then
      step_ok "running (first sync in progress in background)"
      return 0
    fi
    sleep 0.25
  done

  # Not running yet — peek at the launchd state for context but don't fail.
  state="\${state:-spawn-pending}"
  step_warn "daemon state: \$state (it'll keep retrying; check logs at \$STDERR_LOG)"
}

# ==========================================================================
#  Linux: systemd
# ==========================================================================

# Run systemctl in whichever scope we installed into.
systemctl_do() {
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    \$SUDO systemctl "\$@"
  else
    user_systemctl "\$@"
  fi
}

# Drive the TARGET USER's \`systemd --user\` manager.
#
# Two traps, both silent: XDG_RUNTIME_DIR must be set explicitly or
# \`systemctl --user\` dies with "Failed to connect to bus: No medium found";
# and running \`systemctl --user\` AS ROOT talks to ROOT's manager
# (/run/user/0), cheerfully reporting success while doing nothing to the
# user's unit — which is how a scope switch left a second daemon running and
# double-reported the same logs. Drop to the user first.
user_systemctl() {
  local uid
  uid="\$(id -u "\$SERVICE_USER" 2>/dev/null || id -u)"
  if [ "\$(id -u)" = "0" ] && [ "\$SERVICE_USER" != "root" ]; then
    # Args here are always fixed single-word literals, so \$* is safe.
    su -s /bin/sh "\$SERVICE_USER" -c "XDG_RUNTIME_DIR=/run/user/\$uid systemctl --user \$*"
  else
    XDG_RUNTIME_DIR="/run/user/\$uid" systemctl --user "\$@"
  fi
}

# Verify lingering by STATE, never by exit code — the same discipline the
# macOS branch applies to \`launchctl print\`. The marker file is checked FIRST
# because it is where logind persists the setting and what it reads at boot:
# \`loginctl show-user\` answers over D-Bus and fails outright ("User ID N is
# not logged in or lingering") whenever the user object is not instantiated,
# which would read as "linger off" on a machine where it is very much on.
linger_enabled() {
  if [ -e "/var/lib/systemd/linger/\$SERVICE_USER" ]; then return 0; fi
  loginctl show-user "\$SERVICE_USER" -p Linger 2>/dev/null | grep -q '^Linger=yes\$'
}

# --- config-value validation (Linux) ---------------------------------------
# Values that reach daemon.env must survive systemd's EnvironmentFile parser
# unchanged. It strips matching quotes and honors backslash escapes, so a
# value carrying a quote, a newline or edge whitespace is handed to the daemon
# as DIFFERENT BYTES than the operator typed — a --link code that then fails
# with an opaque "link code invalid or expired". Refuse instead of writing a
# file we would read back differently. (macOS gets this for free from the
# plutil -lint backstop on the plist.)
reject_unsafe_env_value() {
  # reject_unsafe_env_value <flag-name> <value>
  case "\$2" in
    *\\"*|*\\'*)
      step_fail "the \$1 value contains a quote — systemd's EnvironmentFile parser would strip it and the daemon would use different bytes than you typed. Re-run with a plain value." ;;
    *[[:cntrl:]]*)
      step_fail "the \$1 value contains a control character (newline/tab) — it cannot be stored in daemon.env unambiguously. Re-run with a plain value." ;;
    " "*|*" ")
      step_fail "the \$1 value has leading or trailing whitespace — systemd would strip it and the daemon would present a different value than you typed. Re-run without it." ;;
  esac
}

# --- step 1: preflight (Linux) --------------------------------------------
# EVERY check that can refuse this machine runs BEFORE the ~36 MB download and
# before anything is written, so a refusal never leaves a half-installed
# daemon behind.
linux_preflight() {
  step_start 1 "Checking this machine"

  # Config values first: they cost nothing to check and a refusal here is a
  # refusal before the download, like every other one in this function.
  reject_unsafe_env_value "--join" "\$JOIN_CODE"
  reject_unsafe_env_value "--company" "\$COMPANY"
  reject_unsafe_env_value "--link" "\$LINK_CODE"

  # sd_booted(3): systemctl can exist while systemd is not PID 1 (containers,
  # WSL1, chroots), so probe the runtime dir, not the binary.
  if [ ! -d /run/systemd/system ]; then
    # The hint has to be self-contained: preflight runs BEFORE the download by
    # design, so \$BIN_DST does not exist yet and "just exec it" would send the
    # user to a file that isn't there.
    step_fail "systemd is not running as init here (no /run/systemd/system), and tokenleader's Linux service is a systemd unit. Nothing was installed. To run it under your own supervisor, fetch the binary yourself:  curl -fsSLo ~/.local/bin/anara-leaderboard \$SERVER_URL/bin/anara-leaderboard-\$ASSET_KEY && chmod +x ~/.local/bin/anara-leaderboard   (verify it against the \$ASSET_KEY sha256 in \$SERVER_URL/manifest.json), then exec it with TOKENLEADER_USER and TOKENLEADER_ENDPOINT set."
  fi
  if ! command -v systemctl >/dev/null 2>&1; then
    step_fail "systemctl not found on PATH. Nothing was installed."
  fi

  # musl: the published binary is glibc (interpreter /lib64/ld-linux-*.so).
  # On Alpine it fails as \`not found\` / status=203/EXEC — a mystifying error
  # that looks like the file is missing. Refuse before the download.
  if ls /lib/ld-musl-* >/dev/null 2>&1 || ldd --version 2>&1 | grep -qi musl; then
    step_fail "this is a musl system (Alpine or similar) and the published binary is glibc-only. Use a glibc distro (Debian, Ubuntu, RHEL/Fedora, Arch). Nothing was installed."
  fi

  # curl is a RUNTIME dependency, not just an install one: the daemon shells
  # out to it for every auto-update download (Bun's fetch is banned on that
  # transfer — it can kill the process with a silent exit(0)). Without curl a
  # Linux daemon reports healthy forever and never takes an update.
  if ! command -v curl >/dev/null 2>&1; then
    step_fail "curl is required — the daemon shells out to it for every auto-update. Install it (apt install curl / dnf install curl / pacman -S curl) and re-run."
  fi
  if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
    step_fail "need sha256sum (coreutils) or shasum to verify the download."
  fi

  if [ "\$SERVICE_SCOPE" = "user" ]; then
    # THE headless-VPS failure: a systemd --user unit is killed within seconds
    # of the session ending unless the user lingers. Enable it and CONFIRM the
    # state; on failure abort with the exact command rather than leaving a
    # daemon that dies at logout.
    if ! linger_enabled; then
      loginctl enable-linger "\$SERVICE_USER" >/dev/null 2>&1 || true
    fi
    if ! linger_enabled; then
      step_fail "systemd --user services are killed at logout unless lingering is on, and this account can't enable it itself. Run:  sudo loginctl enable-linger \$SERVICE_USER   then re-run this installer. (Or re-run the installer with sudo for a system unit, which needs no lingering.) Nothing was installed."
    fi
    if [ ! -d "/run/user/\$(id -u)" ]; then
      step_fail "no /run/user/\$(id -u) even with lingering on — this system is missing libpam-systemd / dbus-user-session, so systemctl --user can't work. Install those, or re-run with sudo for a system unit. Nothing was installed."
    fi
  fi

  # THE dual-scope trap: the box already carries the OTHER scope's unit and we
  # cannot take it down. Installing anyway would leave two resident daemons
  # sharing one state dir (both writing state.json, both running the update
  # swap over one execPath) while every status command reads healthy. Refuse
  # here — before the download — rather than half-installing.
  if [ -f "\$OTHER_UNIT_PATH" ] && ! can_remove_other_scope; then
    step_fail "a systemd unit for tokenleader is already installed at \$OTHER_UNIT_PATH, and removing it needs root — installing a \$SERVICE_SCOPE unit alongside it would leave TWO daemons double-reporting from this machine. Re-run with sudo:  curl -fsSL \$SERVER_URL/install | sudo bash -s -- --name=\$USER_NAME   (or uninstall first: curl -fsSL \$SERVER_URL/uninstall | sudo bash). Nothing was installed."
  fi

  step_ok "systemd \$SERVICE_SCOPE unit for \$SERVICE_USER"
}

# Can this invocation actually tear down the OTHER scope's unit?
#
# The user-scope unit is under the target user's own \$HOME, so we can always
# remove it (we are either that user or root). The system unit under /etc
# needs root — and \$SUDO is EMPTY whenever \`sudo -n true\` failed, which is
# the normal VPS state (password-protected sudo). Answering "yes" there is
# what produced two live daemons: every teardown command failed and every
# failure was swallowed by \`|| true\`.
can_remove_other_scope() {
  if [ "\$SERVICE_SCOPE" = "system" ]; then return 0; fi
  [ "\$(id -u)" = "0" ] || [ -n "\$SUDO" ]
}

# Prove the downloaded binary can actually be EXECUTED by the account the
# unit will run as, before a unit file exists.
#
# noexec on /home (hardened VPS images) and SELinux's user_home_t (RHEL /
# Rocky / Alma, where init_t may not exec from a home dir) both let the
# download succeed and then fail the unit with a bare status=203/EXEC. With
# Restart=always + StartLimitIntervalSec=0 that is a permanent 30s crash loop
# that also survives reboot — so this check must come BEFORE anything is
# enabled, and the diagnosis must name the two causes.
linux_verify_binary_exec() {
  if [ "\$(id -u)" = "0" ] && [ "\$SERVICE_USER" != "root" ]; then
    su -s /bin/sh "\$SERVICE_USER" -c "\\"\$BIN_DST\\" --version" >/dev/null 2>&1
  else
    "\$BIN_DST" --version >/dev/null 2>&1
  fi
}

# --- step 3: unit file + config store (Linux) ------------------------------
write_systemd_unit() {
  step_start 3 "Writing systemd unit"

  # A reinstall must honor THIS server's URL: drop any daemon-written
  # endpoint override. The state dir (TOFU secret) survives reinstalls.
  rm -f "\$STATE_DIR/endpoint"

  # The config store the unit and the CLI share. NOT the unit file: a system
  # unit lives under /etc where an unprivileged \`tokenleader link\` can't be
  # relied on to read it. Deliberately NO TOKENLEADER_HOME — it is a dead key
  # nothing in the daemon reads, and copying it here would invite a state-dir
  # split-brain with TOKENLEADER_STATE_DIR.
  local tmp_env="\$ENV_FILE.tmp.\$\$"
  {
    printf 'TOKENLEADER_USER=%s\\n' "\$USER_NAME"
    printf 'TOKENLEADER_ENDPOINT=%s\\n' "\$SERVER_URL"
    if [ -n "\$JOIN_CODE" ]; then printf 'TOKENLEADER_JOIN=%s\\n' "\$JOIN_CODE"; fi
    if [ -n "\$COMPANY" ];   then printf 'TOKENLEADER_COMPANY=%s\\n' "\$COMPANY"; fi
    if [ -n "\$LINK_CODE" ]; then printf 'TOKENLEADER_LINK=%s\\n' "\$LINK_CODE"; fi
  } >"\$tmp_env"
  chmod 600 "\$tmp_env"
  mv -f "\$tmp_env" "\$ENV_FILE"
  if [ "\$(id -u)" = "0" ]; then
    chown "\$SERVICE_USER:\$SERVICE_GROUP" "\$ENV_FILE"
  fi

  # %h in a SYSTEM unit resolves to the SERVICE MANAGER's home (/root), not
  # User='s — so the system unit uses absolute paths and only the user unit
  # uses %h.
  local unit_body
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    unit_body="User=\$SERVICE_USER
Group=\$SERVICE_GROUP
WorkingDirectory=\$TARGET_HOME
ExecStart=\$TARGET_HOME/.local/bin/anara-leaderboard
EnvironmentFile=\$ENV_FILE"
  else
    unit_body="WorkingDirectory=%h
ExecStart=%h/.local/bin/anara-leaderboard
EnvironmentFile=%h/.local/share/anara-leaderboard/daemon.env"
  fi

  local wanted_by="multi-user.target"
  if [ "\$SERVICE_SCOPE" = "user" ]; then wanted_by="default.target"; fi

  local unit_dir
  unit_dir="\$(dirname "\$UNIT_PATH")"
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    \$SUDO mkdir -p "\$unit_dir"
  else
    mkdir -p "\$unit_dir"
  fi

  # mktemp, not a predictable /tmp name: this branch can run as root.
  local tmp_unit
  tmp_unit="\$(mktemp)"
  cat >"\$tmp_unit" <<UNIT_EOF
[Unit]
Description=tokenleader daemon
Documentation=https://github.com/anaralabs/tokenleader
After=network.target
# NO start-rate limiting. With systemd's defaults (5 starts / 10s) a unit that
# restarts a few times quickly — update swap, restart directive, drift exit —
# latches into 'failed' FOREVER ("Start request repeated too quickly") and
# systemd never tries again. launchd's KeepAlive:true never gives up; systemd
# does. That is the Linux repeat of the v0.5.x fleet-stuck incident, and on
# Linux there is no watchdog to recover from it.
StartLimitIntervalSec=0

[Service]
Type=exec
\$unit_body
# launchd KeepAlive:true parity — respawn on ANY exit: clean, crash, or 75.
# NEVER Restart=on-failure: combined with SuccessExitStatus=75 below it
# classifies the post-update exit as success, declines to restart, and the
# daemon is gone until the next reboot while systemctl status reads healthy.
Restart=always
# launchd ThrottleInterval=30 parity. With StartLimitIntervalSec=0 this is the
# ONLY throttle left, so it must never be lowered to a hot-loop value.
RestartSec=30
# 75 = EX_TEMPFAIL, the daemon's deliberate post-update / restart-directive
# exit. Marking it a success keeps the journal honest ("Deactivated
# successfully" instead of "Failed with result 'exit-code'").
SuccessExitStatus=75
# The daemon writes its own rotating jsonl sink under
# ~/.local/state/anara-leaderboard; stdout would only duplicate it (the macOS
# plist points StandardOutPath at /dev/null for the same reason). stderr goes
# to the journal so crash output the logger never sees is still captured.
StandardOutput=null
StandardError=journal
SyslogIdentifier=tokenleader
Nice=10

[Install]
WantedBy=\$wanted_by
UNIT_EOF

  if [ "\$SERVICE_SCOPE" = "system" ]; then
    \$SUDO install -m 0644 "\$tmp_unit" "\$UNIT_PATH"
  else
    install -m 0644 "\$tmp_unit" "\$UNIT_PATH"
  fi
  rm -f "\$tmp_unit"

  # \`systemd-analyze verify\` is the plutil -lint counterpart. Advisory only:
  # it warns about things (missing man pages, unit ordering) that are not
  # errors, so a non-zero exit must not block an otherwise fine install.
  if command -v systemd-analyze >/dev/null 2>&1; then
    if ! systemd-analyze verify "\$UNIT_PATH" >/dev/null 2>&1; then
      step_warn "systemd-analyze verify had complaints about \$UNIT_PATH (continuing)"
      return 0
    fi
  fi
  step_ok "\$UNIT_PATH"
}

# --- step 4: enable + start (Linux) ----------------------------------------
# No bootout/retry ladder here: systemd's start job is synchronous and
# \`enable --now\` is idempotent, so launchd's async-teardown discipline has
# nothing to port. The verdict is \`is-active\`, not the exit code.
register_systemd_unit() {
  step_start 4 "Enabling systemd service"
  # Never leave BOTH scopes installed: two daemons would double-report the
  # same logs to the leaderboard, race on one state dir, and run the update
  # swap over each other's execPath. A re-run that changes scope tears the
  # other one down first — and the teardown is MANDATORY. It used to end in
  # \`|| true\`, so on the ordinary VPS (password-protected sudo, \$SUDO empty)
  # every command failed silently and the installer reported success with two
  # resident daemons. linux_preflight refuses that case before the download;
  # this is the second gate, verified BY STATE like every launchctl step.
  if [ -f "\$OTHER_UNIT_PATH" ]; then
    if [ "\$SERVICE_SCOPE" = "system" ]; then
      user_systemctl disable --now "\$UNIT" >/dev/null 2>&1 || true
      rm -f "\$OTHER_UNIT_PATH" 2>/dev/null || true
      user_systemctl daemon-reload >/dev/null 2>&1 || true
    else
      \$SUDO systemctl disable --now "\$UNIT" >/dev/null 2>&1 || true
      \$SUDO rm -f "\$OTHER_UNIT_PATH" 2>/dev/null || true
      \$SUDO systemctl daemon-reload >/dev/null 2>&1 || true
    fi
    if [ -f "\$OTHER_UNIT_PATH" ]; then
      step_fail "the other scope's unit is still installed at \$OTHER_UNIT_PATH — two daemons would double-report from this machine. Remove it first (sudo systemctl disable --now \$UNIT && sudo rm \$OTHER_UNIT_PATH), or re-run this installer with sudo."
    fi
  fi
  if ! systemctl_do daemon-reload; then
    step_fail "systemctl daemon-reload failed"
  fi
  # A reinstall over a running unit: restart so the new binary + env take
  # effect now rather than at the next boot.
  if ! systemctl_do enable --now "\$UNIT"; then
    # \`enable --now\` already created the multi-user.target.wants symlink, and
    # StartLimitIntervalSec=0 means systemd NEVER gives up: leaving now would
    # strand a unit that crash-loops every 30s and comes back at every boot.
    # Undo it and hand the operator the journal that explains the failure.
    rollback_systemd_unit "systemctl enable --now \$UNIT failed"
  fi
  systemctl_do restart "\$UNIT" >/dev/null 2>&1 || true
  step_ok
}

# Undo a failed enable: nothing enabled, nothing left crash-looping, and the
# real error (which \`systemctl enable --now\` only summarises) in the output.
rollback_systemd_unit() {
  local why="\$1"
  local tail_out=""
  if command -v journalctl >/dev/null 2>&1; then
    if [ "\$SERVICE_SCOPE" = "system" ]; then
      tail_out="\$(\$SUDO journalctl -u "\$UNIT" -n 20 --no-pager 2>/dev/null || true)"
    else
      tail_out="\$(XDG_RUNTIME_DIR="/run/user/\$(id -u)" journalctl --user -u "\$UNIT" -n 20 --no-pager 2>/dev/null || true)"
    fi
  fi
  systemctl_do disable --now "\$UNIT" >/dev/null 2>&1 || true
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    \$SUDO rm -f "\$UNIT_PATH" 2>/dev/null || true
  else
    rm -f "\$UNIT_PATH" 2>/dev/null || true
  fi
  systemctl_do daemon-reload >/dev/null 2>&1 || true
  systemctl_do reset-failed "\$UNIT" >/dev/null 2>&1 || true
  if [ -n "\$tail_out" ]; then
    printf "%s\\n" "\$tail_out" >&2
  fi
  step_fail "\$why — the unit was removed again, so nothing is left enabled or crash-looping. The journal above has the reason; a status=203/EXEC line means the binary at \$BIN_DST can't be executed by \$SERVICE_USER (noexec mount, or SELinux — try 'restorecon -v \$BIN_DST' or install under /usr/local/lib)."
}

# --- step 5: start daemon (Linux) ------------------------------------------
wait_for_first_tick_linux() {
  step_start 5 "Starting daemon"
  local deadline=\$(( \$(date +%s) + 5 ))
  while [ "\$(date +%s)" -lt "\$deadline" ]; do
    if systemctl_do is-active --quiet "\$UNIT"; then
      step_ok "running (first sync in progress in background)"
      return 0
    fi
    sleep 0.25
  done
  local state
  state="\$(systemctl_do is-active "\$UNIT" 2>/dev/null || true)"
  step_warn "daemon state: \${state:-unknown} (it'll keep retrying; \$(journal_cmd))"
}

journal_cmd() {
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    printf 'journalctl -u tokenleader -f'
  else
    printf 'journalctl --user -u tokenleader -f'
  fi
}

# Ping /stats/admin to confirm the server saw our handle. Non-fatal.
verify_on_server() {
  local body
  body="\$(curl -fsS --max-time 5 "\$SERVER_URL/stats/admin" 2>/dev/null || true)"
  if [ -z "\$body" ]; then
    printf "        %s↳ server check skipped (couldn't reach %s)%s\\n" \\
      "\$C_DIM" "\$SERVER_URL/stats/admin" "\$C_RESET"
    return 0
  fi
  # Cheap substring match for the username; avoids a JSON parser dep.
  if printf "%s" "\$body" | grep -q "\\\"user\\\":\\\"\$USER_NAME\\\""; then
    printf "        %s↳ %sserver saw your batch%s%s\\n" \\
      "\$C_DIM" "\$C_GREEN" "\$C_RESET" "\$C_DIM"
  else
    printf "        %s↳ server reachable; your batch hasn't landed yet%s\\n" \\
      "\$C_DIM" "\$C_RESET"
  fi
}

# --- summary --------------------------------------------------------------
print_summary() {
  printf "\\n%s\\n\\n" "\$DIVIDER"
  printf "  %sinstalled as%s     %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$USER_NAME" "\$C_RESET"
  printf "  %sendpoint%s         %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
  if [ "\$TL_OS" = "darwin" ]; then
    printf "  %slogs%s             %s~/Library/Logs/anara-leaderboard/stderr.log%s\\n" \\
      "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$C_RESET"
  else
    printf "  %slogs%s             %s%s%s  %s(and %s)%s\\n" \\
      "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$LOG_DIR/daemon.jsonl" "\$C_RESET" \\
      "\$C_DIM" "\$(journal_cmd)" "\$C_RESET"
    printf "  %sservice%s          %s%s%s\\n" \\
      "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$UNIT_PATH" "\$C_RESET"
  fi
  # A system unit lives under /etc: removing it needs the same root the
  # install did. Advertising the sudo-less form there sent the operator into
  # a half-run uninstall that had already told the server the device was gone.
  local uninstall_pipe="bash"
  if [ "\$TL_OS" = "linux" ] && [ "\$SERVICE_SCOPE" = "system" ]; then
    uninstall_pipe="sudo bash"
  fi
  printf "  %suninstall%s        %scurl -fsSL %s/uninstall | %s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$SERVER_URL" "\$uninstall_pipe" "\$C_RESET"
  printf "\\n  %sYour usage will appear on the leaderboard within a minute.%s\\n\\n" \\
    "\$C_GREEN" "\$C_RESET"
}

# --- ensure dirs exist before any step touches them -----------------------
ensure_dirs() {
  if [ "\$TL_OS" = "darwin" ]; then
    mkdir -p "\$HOME/.local/bin" \\
             "\$HOME/Library/LaunchAgents" \\
             "\$LOG_DIR" \\
             "\$STATE_DIR"
    return 0
  fi
  # Root-run install: EVERY level we create must end up owned by the service
  # user. Chowning only ~/.local/bin and leaving ~/.local root-owned makes the
  # daemon crash-loop with EACCES on mkdir '~/.local/share'.
  local d
  for d in "\$TARGET_HOME/.local" \\
           "\$TARGET_HOME/.local/bin" \\
           "\$TARGET_HOME/.local/share" \\
           "\$TARGET_HOME/.local/state" \\
           "\$STATE_DIR" \\
           "\$LOG_DIR"; do
    if [ "\$(id -u)" != "0" ]; then
      mkdir -p "\$d"
    elif [ -d "\$d" ]; then
      # NEVER re-mode a directory that already exists: \`install -d -m 0755\`
      # over the whole ~/.local chain silently widened a user's private
      # 0700 ~/.local (and everything another app keeps under it) to
      # world-readable. Ownership is all we need from a pre-existing dir.
      chown "\$SERVICE_USER:\$SERVICE_GROUP" "\$d" 2>/dev/null || true
    else
      install -d -m 0755 -o "\$SERVICE_USER" -g "\$SERVICE_GROUP" "\$d"
    fi
  done
}

# sha256 of a file. coreutils' sha256sum is on every Linux and absent from a
# stock macOS; shasum is a macOS-bundled perl script often absent from a
# minimal Debian. Try both.
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "\$1" | awk '{print \$1}'
  else
    shasum -a 256 "\$1" | awk '{print \$1}'
  fi
}
`;
}

/**
 * Installer that downloads the binary from the server's own BinaryMirror
 * cache — the server is the single network dep for install, ingest and
 * auto-update. The sha256 check is transport integrity only: manifest and
 * binary come from the same server.
 */
export function renderInstallScript(serverUrl: string, opts: InstallScriptOpts = {}): string {
  const url = trimTrailingSlash(serverUrl);
  // Surface a missing join code before doing any work; existing handles
  // reinstall fine without one (their TOFU secret rules).
  const joinWarning = opts.joinRequired
    ? `if [ -z "\$JOIN_CODE" ]; then
  printf "  %s!%s this server requires a join code for NEW handles; without one the daemon's first sync will 403.\\n" "\$C_YELLOW" "\$C_RESET"
  printf "    re-run with: %scurl -fsSL %s/install | bash -s -- --join=<code>%s\\n\\n" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
fi
`
    : "";
  return `${renderSharedBashPreamble(url, opts)}
# Dev/staging escape hatch; default is the server's own /bin route.
BINARY_BASE_URL="\${TOKENLEADER_BINARY_URL:-\$SERVER_URL/bin}"

# --- step 2: download binary ----------------------------------------------
# manifest.json first so the binary sha256 is verified before the swap.
# Both 503 until the server's first successful mirror tick.
do_download() {
  step_start 2 "Downloading daemon binary"
  local tmp_bin="\$BIN_DST.tmp.\$\$"
  local tmp_manifest="\$BIN_DST.manifest.\$\$.json"
  local arch_asset="anara-leaderboard-\$ASSET_KEY"

  if ! curl -fsSL --max-time 30 "\$SERVER_URL/manifest.json" -o "\$tmp_manifest"; then
    rm -f "\$tmp_manifest"
    step_fail "couldn't fetch \$SERVER_URL/manifest.json (the server 503s until its binary mirror has fetched a release)"
  fi

  # No jq dep. python3 is the clean path WHEN PRESENT — but macOS has not
  # shipped python3 by default since 12.3 (only with Xcode CLT), so the sed
  # fallback below MUST stand on its own for non-developer Macs.
  # Both shapes: darwin's key is top-level, linux's lives under .platforms.
  local expected_sha=""
  if command -v python3 >/dev/null 2>&1; then
    expected_sha="\$(python3 -c "import json,sys; m=json.load(open(sys.argv[1])); k=sys.argv[2]; e=m.get(k) or m.get('platforms',{}).get(k); print(e['sha256'])" "\$tmp_manifest" "\$ASSET_KEY" 2>/dev/null || true)"
  fi
  if [ -z "\$expected_sha" ]; then
    # BSD-sed-compatible (GNU sed accepts the same -E expression): collapse to
    # one line, extract our key's sha256. The leading quote in "\$ASSET_KEY"
    # is what keeps "x64" from matching inside "darwin-x64"/"linux-x64".
    # [[:space:]]* around the colon tolerates a PRETTY-PRINTED manifest
    # ("sha256": "…" with a space) as well as compact ("sha256":"…").
    expected_sha="\$(tr -d '\\n\\r' < "\$tmp_manifest" \\
      | sed -E "s/.*\\"\$ASSET_KEY\\"[^}]*\\"sha256\\"[[:space:]]*:[[:space:]]*\\"([0-9a-fA-F]{64})\\".*/\\1/" \\
      | grep -E '^[0-9a-fA-F]{64}\$' || true)"
  fi
  if [ -z "\$expected_sha" ]; then
    rm -f "\$tmp_manifest"
    step_fail "couldn't parse sha256 for \$ASSET_KEY out of manifest.json (does this server's release carry a \$ASSET_KEY build?)"
  fi

  # Stop the spinner before curl draws its own progress bar.
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[2/%d]%s Downloading daemon binary  %s↓%s\\n" \\
      "\$C_BOLD" "\$TOTAL_STEPS" "\$C_RESET" "\$C_DIM" "\$C_RESET"
  fi
  # curl -# = built-in progress bar; -f = fail on 4xx/5xx; -L = follow redirects.
  # Linux binaries are ~94 MB raw and ~36 MB gzipped, so the Linux branch asks
  # for the compressed representation; curl decodes before writing, leaving the
  # sha comparison below untouched. The macOS request is left exactly as it
  # was.
  local bin_url="\$BINARY_BASE_URL/\$arch_asset"
  local dl_ok=0
  if [ "\$TL_OS" = "linux" ]; then
    if curl -#fL --compressed "\$bin_url" -o "\$tmp_bin"; then dl_ok=1; fi
  else
    if curl -#fL "\$bin_url" -o "\$tmp_bin"; then dl_ok=1; fi
  fi
  if [ "\$dl_ok" != "1" ]; then
    rm -f "\$tmp_bin" "\$tmp_manifest"
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloading daemon binary"
    step_fail "download failed from \$bin_url (is the server reachable?)"
  fi

  local actual_sha
  actual_sha="\$(sha256_of "\$tmp_bin")"
  if [ "\$actual_sha" != "\$expected_sha" ]; then
    rm -f "\$tmp_bin" "\$tmp_manifest"
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloading daemon binary"
    step_fail "sha256 mismatch on \$arch_asset (expected \$expected_sha, got \$actual_sha)"
  fi

  chmod +x "\$tmp_bin"
  mv -f "\$tmp_bin" "\$BIN_DST"
  rm -f "\$tmp_manifest"

  # The documented CLI name (\`tokenleader link\` etc.) beside the legacy
  # binary name the fleet depends on. Only create/replace when missing or
  # already a symlink — never clobber a real file that owns the name.
  if [ ! -e "\$TARGET_HOME/.local/bin/tokenleader" ] || [ -L "\$TARGET_HOME/.local/bin/tokenleader" ]; then
    ln -sfn "\$BIN_DST" "\$TARGET_HOME/.local/bin/tokenleader"
  fi

  # Root-run Linux install: hand the artifacts to the service user.
  if [ "\$TL_OS" = "linux" ] && [ "\$(id -u)" = "0" ]; then
    chown "\$SERVICE_USER:\$SERVICE_GROUP" "\$BIN_DST"
    chown -h "\$SERVICE_USER:\$SERVICE_GROUP" "\$TARGET_HOME/.local/bin/tokenleader" 2>/dev/null || true
  fi

  # Downloaded and +x is not the same as RUNNABLE BY THE SERVICE USER. Prove
  # it here, while the only thing on disk is the binary itself — a unit that
  # cannot exec its ExecStart crash-loops forever under Restart=always.
  if [ "\$TL_OS" = "linux" ] && ! linux_verify_binary_exec; then
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloading daemon binary"
    step_fail "\$BIN_DST downloaded but '\$BIN_DST --version' will not run as \$SERVICE_USER. Usually a noexec mount on \$TARGET_HOME, or SELinux labelling (try 'restorecon -v \$BIN_DST'). No service was installed."
  fi

  # curl's bar left the cursor on a fresh line; emit the success line.
  if [ -t 1 ]; then
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloaded daemon binary"
    printf "  %s[2/%d]%s Downloaded daemon binary  %s…………%s %s✓%s\\n" \\
      "\$C_BOLD" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$C_DIM" "\$C_RESET" "\$C_GREEN" "\$C_RESET"
  else
    printf "  [2/%d] downloaded\\n" "\$TOTAL_STEPS"
  fi
}

# --- main -----------------------------------------------------------------
resolve_handle
print_banner
${joinWarning}if [ "\$TL_OS" = "darwin" ]; then
  ensure_dirs
  do_download
  do_codesign
  write_plist_and_register
  write_watchdog_plist_and_register
  wait_for_first_tick
else
  linux_preflight
  ensure_dirs
  do_download
  write_systemd_unit
  register_systemd_unit
  wait_for_first_tick_linux
fi
print_summary
`;
}

export function renderUninstallScript(serverUrl: string): string {
  const url = trimTrailingSlash(serverUrl);
  return `#!/usr/bin/env bash
# tokenleader self-serve uninstaller.
# Generated by the tokenleader server at ${url}.
set -euo pipefail

SERVER_URL="\${TOKENLEADER_INSTALL_URL:-${url}}"

# --- color setup ----------------------------------------------------------
if [ -t 1 ]; then
  C_RESET=$'\\033[0m'
  C_BOLD=$'\\033[1m'
  C_DIM=$'\\033[2m'
  C_GREEN=$'\\033[0;32m'
  C_YELLOW=$'\\033[0;33m'
  C_RED=$'\\033[0;31m'
else
  C_RESET=""; C_BOLD=""; C_DIM=""
  C_GREEN=""; C_YELLOW=""; C_RED=""
fi
info() { printf "  %s→%s %s\\n" "\$C_DIM" "\$C_RESET" "\$*"; }
ok()   { printf "  %s✓%s %s\\n" "\$C_GREEN" "\$C_RESET" "\$*"; }
warn() { printf "  %s!%s %s\\n" "\$C_YELLOW" "\$C_RESET" "\$*" >&2; }
err()  { printf "  %s✗%s %s\\n" "\$C_RED" "\$C_RESET" "\$*" >&2; }

OS_NAME="\$(uname -s)"
case "\$OS_NAME" in
  Darwin) TL_OS="darwin" ;;
  Linux)  TL_OS="linux" ;;
  *) err "This uninstaller supports macOS and Linux. Detected: \$OS_NAME."; exit 1 ;;
esac

# Reopen stdin from the tty when piped through bash, so the purge prompt can
# be answered. The subshell probe is load-bearing: /dev/tty can exist and pass
# -r while being unopenable (a detached session, docker exec with no -t, cron,
# a systemd unit). \`exec\` redirection failure kills a non-interactive shell
# outright and \`|| true\` does NOT catch it, so the uninstaller would die
# before it even notified the server. Failing the probe just leaves stdin
# alone; TOKENLEADER_PURGE answers the prompt non-interactively.
if [ ! -t 0 ] && [ -r /dev/tty ] && (: </dev/tty) 2>/dev/null; then
  exec </dev/tty
fi

printf "\\n  %stokenleader uninstaller%s\\n\\n" "\$C_BOLD" "\$C_RESET"

LABEL="${LABEL}"
WATCHDOG_LABEL="\${LABEL}.watchdog"
DOMAIN="gui/\$(id -u)"
UNIT="${UNIT}"
PLIST="\$HOME/Library/LaunchAgents/\${LABEL}.plist"
WATCHDOG_PLIST="\$HOME/Library/LaunchAgents/\${WATCHDOG_LABEL}.plist"

# Linux: mirror the installer's target-user resolution so \`sudo bash\` cleans
# up the human's install, not root's.
SUDO=""
SERVICE_USER=""
TARGET_HOME="\$HOME"
SERVICE_SCOPE=""
UNIT_PATH=""
if [ "\$TL_OS" = "linux" ]; then
  if [ "\$(id -u)" = "0" ]; then
    SERVICE_USER="\${SUDO_USER:-root}"
  else
    SERVICE_USER="\$(id -un)"
    if sudo -n true 2>/dev/null; then SUDO="sudo -n"; fi
  fi
  if command -v getent >/dev/null 2>&1; then
    TARGET_HOME="\$(getent passwd "\$SERVICE_USER" | cut -d: -f6)"
  fi
  if [ -z "\$TARGET_HOME" ] && [ "\$SERVICE_USER" = "\$(id -un)" ]; then TARGET_HOME="\$HOME"; fi
  # Whichever scope is actually installed wins over any default.
  if [ -f "/etc/systemd/system/\$UNIT" ]; then
    SERVICE_SCOPE="system"; UNIT_PATH="/etc/systemd/system/\$UNIT"
  elif [ -f "\$TARGET_HOME/.config/systemd/user/\$UNIT" ]; then
    SERVICE_SCOPE="user"; UNIT_PATH="\$TARGET_HOME/.config/systemd/user/\$UNIT"
  fi
fi

# --- privilege preflight (Linux) ------------------------------------------
# A system unit lives under /etc and needs root to disable and delete. Without
# this gate, \`curl … /uninstall | bash\` on a system-scope box POSTed the
# uninstall to the server FIRST and only then died on \`rm: Permission denied\`
# (set -e) — leaving a running, re-registering daemon behind a device the
# server had already retired. Refuse before touching anything.
linux_uninstall_preflight() {
  [ "\$TL_OS" = "linux" ] || return 0
  [ "\$SERVICE_SCOPE" = "system" ] || return 0
  [ "\$(id -u)" != "0" ] || return 0
  [ -z "\$SUDO" ] || return 0
  err "This machine runs the SYSTEM unit at \$UNIT_PATH; removing it needs root."
  err "Re-run as:  curl -fsSL \$SERVER_URL/uninstall | sudo bash"
  err "Nothing was changed."
  exit 1
}
linux_uninstall_preflight

BIN="\$TARGET_HOME/.local/bin/anara-leaderboard"
BIN_WATCHDOG="\$BIN.watchdog"
STATE_DIR="\$TARGET_HOME/.local/share/anara-leaderboard"
ENV_FILE="\$STATE_DIR/daemon.env"
if [ "\$TL_OS" = "darwin" ]; then
  LOG_DIR="\$HOME/Library/Logs/anara-leaderboard"
else
  LOG_DIR="\$TARGET_HOME/.local/state/anara-leaderboard"
fi
SECRET_FILE="\$STATE_DIR/secret"

# Same two traps as the installer: XDG_RUNTIME_DIR must be explicit, and
# \`systemctl --user\` run as root targets ROOT's manager, not the user's —
# which would leave a running daemon behind after a "successful" uninstall.
systemctl_do() {
  if [ "\$SERVICE_SCOPE" = "system" ]; then
    \$SUDO systemctl "\$@"
    return
  fi
  local uid
  uid="\$(id -u "\$SERVICE_USER" 2>/dev/null || id -u)"
  if [ "\$(id -u)" = "0" ] && [ "\$SERVICE_USER" != "root" ]; then
    su -s /bin/sh "\$SERVICE_USER" -c "XDG_RUNTIME_DIR=/run/user/\$uid systemctl --user \$*"
  else
    XDG_RUNTIME_DIR="/run/user/\$uid" systemctl --user "\$@"
  fi
}

# --- notify the server BEFORE we delete local state ------------------------
# The service definition (handle) and secret file must still be on disk to
# authenticate the POST. A server outage MUST NOT block local cleanup. The
# handle comes from wherever the platform keeps it — the plist on macOS, the
# EnvironmentFile on Linux — so custom --name handles still get reported.
notify_server_uninstall() {
  local handle=""
  if [ "\$TL_OS" = "darwin" ]; then
    if [ -f "\$PLIST" ]; then
      handle="\$(/usr/libexec/PlistBuddy -c 'Print :EnvironmentVariables:TOKENLEADER_USER' "\$PLIST" 2>/dev/null || true)"
    fi
    if [ -z "\$handle" ] && [ -f "\$PLIST" ]; then
      # PlistBuddy ships with macOS; this awk fallback costs nothing.
      handle="\$(awk '/<key>TOKENLEADER_USER<\\/key>/{getline; gsub(/.*<string>|<\\/string>.*/, ""); print; exit}' "\$PLIST" 2>/dev/null || true)"
    fi
  else
    if [ -r "\$ENV_FILE" ]; then
      handle="\$(sed -n 's/^TOKENLEADER_USER=//p' "\$ENV_FILE" 2>/dev/null | head -1 || true)"
    fi
    if [ -z "\$handle" ] && [ -n "\$UNIT_PATH" ] && [ -r "\$UNIT_PATH" ]; then
      handle="\$(sed -n 's/^Environment=TOKENLEADER_USER=//p' "\$UNIT_PATH" 2>/dev/null | head -1 || true)"
    fi
  fi
  local secret=""
  if [ -r "\$SECRET_FILE" ]; then
    secret="\$(tr -d '[:space:]' < "\$SECRET_FILE" 2>/dev/null || true)"
  fi
  if [ -z "\$handle" ] || [ -z "\$secret" ]; then
    info "Skipping server notify (handle/secret not on disk)."
    return 0
  fi
  info "Notifying server of uninstall for \$handle..."
  local body
  body="\$(printf '{"user":"%s"}' "\$handle")"
  if curl --max-time 5 --fail-with-body -sS \\
       -H "Content-Type: application/json" \\
       -H "X-Tokenleader-Secret: \$secret" \\
       -X POST "\$SERVER_URL/events/uninstall" \\
       --data "\$body" >/dev/null 2>&1; then
    ok "Server acknowledged."
  else
    warn "Server notify failed (continuing with local cleanup)."
  fi
}
notify_server_uninstall

if [ "\$TL_OS" = "darwin" ]; then
  # Watchdog FIRST: its boot-time self-heal re-bootstraps an absent daemon
  # label, so booting the daemon out first invites a resurrection race.
  # Pre-v0.6.0 installs have no watchdog — absence of each is fine.
  info "Stopping watchdog LaunchAgent (if running)..."
  if launchctl bootout "\$DOMAIN/\$WATCHDOG_LABEL" 2>/dev/null; then
    ok  "Booted out \$WATCHDOG_LABEL."
  else
    info "\$WATCHDOG_LABEL was not loaded (pre-v0.6.0 install, or already gone)."
  fi

  info "Stopping LaunchAgent (if running)..."
  if launchctl bootout "\$DOMAIN/\$LABEL" 2>/dev/null; then
    ok  "Booted out \$LABEL."
  else
    warn "\$LABEL was not loaded (or bootout failed); continuing."
  fi

  if [ -f "\$WATCHDOG_PLIST" ]; then
    rm -f "\$WATCHDOG_PLIST"
    ok "Removed \$WATCHDOG_PLIST"
  else
    info "No plist at \$WATCHDOG_PLIST"
  fi

  if [ -f "\$PLIST" ]; then
    rm -f "\$PLIST"
    ok "Removed \$PLIST"
  else
    info "No plist at \$PLIST"
  fi
else
  # disable --now must be as disciplined as launchctl bootout: a unit left
  # enabled is a service systemd keeps restarting after its binary is gone.
  # BOTH scopes are swept — an install that switched scope at some point must
  # not leave the other one behind to resurrect itself.
  REMOVED_ANY=0
  for candidate in "system:/etc/systemd/system/\$UNIT" \\
                   "user:\$TARGET_HOME/.config/systemd/user/\$UNIT"; do
    SERVICE_SCOPE="\${candidate%%:*}"
    UNIT_PATH="\${candidate#*:}"
    [ -f "\$UNIT_PATH" ] || continue
    REMOVED_ANY=1
    info "Stopping and disabling \$UNIT (\$SERVICE_SCOPE scope)..."
    systemctl_do disable --now "\$UNIT" >/dev/null 2>&1 || \\
      warn "systemctl disable --now \$UNIT failed; continuing."
    # No bare \`rm\`: under set -e a permission error here aborted the whole
    # uninstall mid-teardown, after the server had already been notified.
    if [ "\$SERVICE_SCOPE" = "system" ]; then
      \$SUDO rm -f "\$UNIT_PATH" 2>/dev/null || true
    else
      rm -f "\$UNIT_PATH" 2>/dev/null || true
    fi
    if [ -f "\$UNIT_PATH" ]; then
      warn "Couldn't remove \$UNIT_PATH (need root? re-run: curl -fsSL \$SERVER_URL/uninstall | sudo bash)"
    else
      ok "Removed \$UNIT_PATH"
    fi
    systemctl_do daemon-reload >/dev/null 2>&1 || true
    systemctl_do reset-failed "\$UNIT" >/dev/null 2>&1 || true
  done
  if [ "\$REMOVED_ANY" = "0" ]; then
    info "No systemd unit found (already uninstalled?)."
  fi
fi

if [ -f "\$BIN" ]; then
  rm -f "\$BIN"
  ok "Removed \$BIN"
else
  info "No binary at \$BIN"
fi

# The .watchdog hardlink shares the daemon binary's inode; remove it too or
# the watchdog's plist would keep a runnable copy alive after uninstall.
# (macOS only — Linux never installs a watchdog.)
if [ -f "\$BIN_WATCHDOG" ]; then
  rm -f "\$BIN_WATCHDOG"
  ok "Removed \$BIN_WATCHDOG"
fi

# The CLI-name symlink the installer (or daemon) created beside the binary.
if [ -L "\$TARGET_HOME/.local/bin/tokenleader" ]; then
  rm -f "\$TARGET_HOME/.local/bin/tokenleader"
  ok "Removed \$TARGET_HOME/.local/bin/tokenleader"
fi

ANSWER="\${TOKENLEADER_PURGE:-}"
if [ -z "\$ANSWER" ]; then
  printf "\\n  Also delete daemon state %s%s%s and logs %s%s%s? [y/N] " \\
    "\$C_BOLD" "\$STATE_DIR" "\$C_RESET" \\
    "\$C_BOLD" "\$LOG_DIR" "\$C_RESET"
  read -r ANSWER || ANSWER=""
fi
case "\$ANSWER" in
  y|Y|yes|YES)
    rm -rf "\$STATE_DIR" "\$LOG_DIR"
    ok "Removed state and logs."
    ;;
  *)
    # The endpoint override is server-instance-specific; only the TOFU
    # secret is worth preserving across installs.
    rm -f "\$STATE_DIR/endpoint"
    info "Keeping \$STATE_DIR and \$LOG_DIR."
    ;;
esac

printf "\\n  %s✓ uninstall complete.%s\\n\\n" "\$C_GREEN" "\$C_RESET"
`;
}

// scripts/install.sh keeps its own copy of this preamble (it is NOT sourced
// from here); this export exists for tests/tooling.
export { renderSharedBashPreamble };
